// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: author/v1/author.proto

package authorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_author_v1_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_author_v1_author_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthorRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_author_v1_author_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_author_v1_author_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_author_v1_author_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_author_v1_author_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

var File_author_v1_author_proto protoreflect.FileDescriptor

const file_author_v1_author_proto_rawDesc = "" +
	"\n" +
	"\x16author/v1/author.proto\x12\tauthor.v1\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\">\n" +
	"\x11GetAuthorResponse\x12)\n" +
	"\x06author\x18\x01 \x01(\v2\x11.author.v1.AuthorR\x06author\"B\n" +
	"\x13ListAuthorsResponse\x12+\n" +
	"\aauthors\x18\x01 \x03(\v2\x11.author.v1.AuthorR\aauthors2\xa2\x01\n" +
	"\rAuthorService\x12H\n" +
	"\tGetAuthor\x12\x1b.author.v1.GetAuthorRequest\x1a\x1c.author.v1.GetAuthorResponse\"\x00\x12G\n" +
	"\vListAuthors\x12\x16.google.protobuf.Empty\x1a\x1e.author.v1.ListAuthorsResponse\"\x00B]\n" +
	"!org.noxhalley.contracts.author.v1Z8github.com/noxhalley/contracts/gen/go/author/v1;authorv1b\x06proto3"

var (
	file_author_v1_author_proto_rawDescOnce sync.Once
	file_author_v1_author_proto_rawDescData []byte
)

func file_author_v1_author_proto_rawDescGZIP() []byte {
	file_author_v1_author_proto_rawDescOnce.Do(func() {
		file_author_v1_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_author_v1_author_proto_rawDesc), len(file_author_v1_author_proto_rawDesc)))
	})
	return file_author_v1_author_proto_rawDescData
}

var file_author_v1_author_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_author_v1_author_proto_goTypes = []any{
	(*Author)(nil),              // 0: author.v1.Author
	(*GetAuthorRequest)(nil),    // 1: author.v1.GetAuthorRequest
	(*GetAuthorResponse)(nil),   // 2: author.v1.GetAuthorResponse
	(*ListAuthorsResponse)(nil), // 3: author.v1.ListAuthorsResponse
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_author_v1_author_proto_depIdxs = []int32{
	0, // 0: author.v1.GetAuthorResponse.author:type_name -> author.v1.Author
	0, // 1: author.v1.ListAuthorsResponse.authors:type_name -> author.v1.Author
	1, // 2: author.v1.AuthorService.GetAuthor:input_type -> author.v1.GetAuthorRequest
	4, // 3: author.v1.AuthorService.ListAuthors:input_type -> google.protobuf.Empty
	2, // 4: author.v1.AuthorService.GetAuthor:output_type -> author.v1.GetAuthorResponse
	3, // 5: author.v1.AuthorService.ListAuthors:output_type -> author.v1.ListAuthorsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_author_v1_author_proto_init() }
func file_author_v1_author_proto_init() {
	if File_author_v1_author_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_author_v1_author_proto_rawDesc), len(file_author_v1_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_author_v1_author_proto_goTypes,
		DependencyIndexes: file_author_v1_author_proto_depIdxs,
		MessageInfos:      file_author_v1_author_proto_msgTypes,
	}.Build()
	File_author_v1_author_proto = out.File
	file_author_v1_author_proto_goTypes = nil
	file_author_v1_author_proto_depIdxs = nil
}
